spring:
  application:
    name: craftly-eureka
  server:
    port: 8761
  eureka:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      prefer-ip-address: true
    client:
      register-with-eureka: false
      fetch-registry: false
    server:
      use-read-only-response-cache: false
  logging:
    level:
      com.netflix.discovery: DEBUG
      org.springframework.cloud.netflix.eureka: DEBUG