server:
  port: 8083

spring:
  application:
    name: saga-module
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true

temporal:
  host: 127.0.0.1:7233

logging:
  level:
    root: INFO
    io.temporal: DEBUG
